In [98]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [100]:
df=pd.read_csv("C:/Users/HP/OneDrive/Desktop/SENTIMENT BALANCED REVIEW DATASET.CSV")

In [101]:
df

,overall,reviewText,summary
0,5,"I'm enjoying these, the fit is about right and...",Very comfortable
1,5,these are the coolest little board shorts. Th...,funky board short
2,5,"beautiful ring for the money, looks very expen...",Five Stars
3,5,"I love this dress! Fantastic quality, great st...",I love this dress
4,5,These Ecco golf shoes are differently shaped t...,Still A Great Fit!
...,...,...,...
791995,1,Its just like every other shaper uncomfortable...,Just like other shapers
791996,1,The fit is fine and they're comfortable. Howev...,Disappointing Quality
791997,1,correct size but pops open very easily,not the best
791998,1,Only rated this with one star because you didn...,Dont waste your money!
791999,1,The product came without the tags on the side!!!,Wrong product

In [102]:
df.shape

(792000, 3)

In [106]:
df.head()

,overall,reviewText,summary
0,5,"I'm enjoying these, the fit is about right and...",Very comfortable
1,5,these are the coolest little board shorts. Th...,funky board short
2,5,"beautiful ring for the money, looks very expen...",Five Stars
3,5,"I love this dress! Fantastic quality, great st...",I love this dress
4,5,These Ecco golf shoes are differently shaped t...,Still A Great Fit!

In [108]:
df.isnull().sum()

overall         0
reviewText    614
summary       256
dtype: int64

df['overall'].value_counts()

In [110]:
df['overall'].value_counts()

overall
3    264000
5    132000
4    132000
2    132000
1    132000
Name: count, dtype: int64

In [112]:
df.info

<bound method DataFrame.info of         overall                                         reviewText  \
0             5  I'm enjoying these, the fit is about right and...
1             5  these are the coolest little board shorts.  Th...
2             5  beautiful ring for the money, looks very expen...
3             5  I love this dress! Fantastic quality, great st...
4             5  These Ecco golf shoes are differently shaped t...
...         ...                                                ...
791995        1  Its just like every other shaper uncomfortable...
791996        1  The fit is fine and they're comfortable. Howev...
791997        1             correct size but pops open very easily
791998        1  Only rated this with one star because you didn...
791999        1   The product came without the tags on the side!!!

                        summary
0              Very comfortable
1             funky board short
2                    Five Stars
3             I love this dress
4            Still A Great Fit!
...                         ...
791995  Just like other shapers
791996    Disappointing Quality
791997             not the best
791998   Dont waste your money!
791999            Wrong product

[792000 rows x 3 columns]>

In [114]:
df.isnull().any(axis=1)

0         False
1         False
2         False
3         False
4         False
          ...
791995    False
791996    False
791997    False
791998    False
791999    False
Length: 792000, dtype: bool

In [116]:
df.shape

(792000, 3)

In [118]:
df.columns

Index(['overall', 'reviewText', 'summary'], dtype='object')

In [120]:
df.columns.tolist() # isse columns ko list mai dikhata hai..

['overall', 'reviewText', 'summary']

In [122]:
df["overall"].value_counts()

overall
3    264000
5    132000
4    132000
2    132000
1    132000
Name: count, dtype: int64

In [124]:
df.isnull().any(axis=0)

overall       False
reviewText     True
summary        True
dtype: bool

In [126]:
df[df.isnull().any(axis=1)]

,overall,reviewText,summary
352,5,NaN,Five Stars
1232,5,NaN,Five Stars
2113,5,NaN,Five Stars
5324,4,"Showed up on time, great shoe",NaN
7143,4,NaN,Had the bracelet for more than month and it ha...
...,...,...,...
788309,1,Way toooo small in breast area....ABSOLUTELY N...,NaN
788567,1,NaN,One Star
789115,1,NaN,One Star
789237,1,NaN,One Star
791010,1,They tore within minutes. :/ on the bottom,NaN

In [128]:
df.dropna(inplace=True)

In [130]:
df.shape

(791143, 3)

In [132]:
df['overall'].value_counts()

overall
3    263815
2    131916
1    131860
4    131832
5    131720
Name: count, dtype: int64

In [134]:
df=df[df['overall']!=3] # execpt 3 rating

In [144]:
df.shape

(527328, 3)

In [146]:
df["overall"].value_counts()

overall
2    131916
1    131860
4    131832
5    131720
Name: count, dtype: int64

In [148]:
import numpy as np

In [150]:
np.where(df["overall"]>3,1,0)

array([1, 1, 1, ..., 0, 0, 0])

In [152]:
df["positivity"]=np.where(df["overall"]>3,1,0)

C:\Users\HP\AppData\Local\Temp\ipykernel_15356\4111429597.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df["positivity"]=np.where(df["overall"]>3,1,0)

In [154]:
df.shape

(527328, 4)

In [156]:
df["positivity"].value_counts()

positivity
0    263776
1    263552
Name: count, dtype: int64

In [158]:
df.columns.tolist()

['overall', 'reviewText', 'summary', 'positivity']

In [160]:
df["reviewText"].head()

0    I'm enjoying these, the fit is about right and...
1    these are the coolest little board shorts.  Th...
2    beautiful ring for the money, looks very expen...
3    I love this dress! Fantastic quality, great st...
4    These Ecco golf shoes are differently shaped t...
Name: reviewText, dtype: object

In [162]:
df

,overall,reviewText,summary,positivity
0,5,"I'm enjoying these, the fit is about right and...",Very comfortable,1
1,5,these are the coolest little board shorts. Th...,funky board short,1
2,5,"beautiful ring for the money, looks very expen...",Five Stars,1
3,5,"I love this dress! Fantastic quality, great st...",I love this dress,1
4,5,These Ecco golf shoes are differently shaped t...,Still A Great Fit!,1
...,...,...,...,...
791995,1,Its just like every other shaper uncomfortable...,Just like other shapers,0
791996,1,The fit is fine and they're comfortable. Howev...,Disappointing Quality,0
791997,1,correct size but pops open very easily,not the best,0
791998,1,Only rated this with one star because you didn...,Dont waste your money!,0
791999,1,The product came without the tags on the side!!!,Wrong product,0

In [164]:
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

In [166]:
# Split the data into features (X) and target (y)
X = df['reviewText']
Y = df['positivity']

In [168]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [170]:
x_train.shape,x_test.shape # is trah se ek hi column mai train test data dekh skte hai..

((421862,), (105466,))

In [172]:
y_train.shape, y_test.shape # is trah se ek hi sath train and test data dekh skte hai..

((421862,), (105466,))

In [174]:
# Convert text data to TF-IDF features
tfidf = TfidfVectorizer(max_features=5000)  # tfidf = to bag of wirds . ye thoda fast rehta hai bow se
x_train_tfidf = tfidf.fit_transform(x_train)
x_test_tfidf = tfidf.transform(x_test)

In [175]:
# Train a Logistic Regression model
model = LogisticRegression()
model.fit(x_train_tfidf, y_train)

LogisticRegression()

In [176]:
y_pred = model.predict(x_test_tfidf)

In [177]:
y_pred

array([1, 0, 1, ..., 1, 1, 0])

In [178]:
# Evaluate the model
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))

Accuracy: 0.9006409648607134
Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.91      0.90     52534
           1       0.91      0.89      0.90     52932

    accuracy                           0.90    105466
   macro avg       0.90      0.90      0.90    105466
weighted avg       0.90      0.90      0.90    105466

Confusion Matrix:
 [[47754  4780]
 [ 5699 47233]]

In [184]:
# Example prediction
new_reviews = ["The product is great!", "I am not satisfied with this item."] # ye data apne pass se dia hai...
new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1 0]

In [186]:
# Example prediction
new_reviews = ["Great nephew loved!!! Very fast delivery!!!!!"]
new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [188]:
Perfect fit. Good quality. (Do not put in dryer.)

SyntaxError: invalid syntax (3293591732.py, line 1)

In [190]:
# Example prediction
new_reviews = ["Perfect fit. Good quality. (Do not put in dryer.)"]
new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [192]:
# Example prediction
new_reviews=["these are the coolest little board shorts. They have adjustable an waist, which is perfect for my slim little guy.Good quality"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [194]:
new_reviews=["though the product is good,but not upto my expectations"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [196]:
new_reviews=["this laptop is loaded with new features but the batterys is dying so fast"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [198]:
new_reviews=["though the product is good but not upto my expectations"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [200]:
x_train

47516     Product has cheep itchy material and runs smal...
631       Love this watch. I have a real expensive diamo...
475165    I wear a 2 gauge. I love the spiral ear plugs....
671187                                           disgusting
22154           The sand me different sandal different size
                                ...
544224                             Didn't fit as expected .
232526    The quality of the shirt does not justify its ...
174108                            It's good for the price !
652381    The overall rings are a bit smaller than I exp...
458084    This was one of the holiday gifts I purchased ...
Name: reviewText, Length: 421862, dtype: object

In [202]:
# Add a new column 'sentiment_label' based on the 'positivity' column
df['sentiment_label'] = np.where(df['positivity'] == 1, 'positivity', 'negative') # jahan pr positivity column mai 1 hai 
# wahan par positive dega , agr 1 nhi hai to negative dega . sentiment label mai

# Display the first few rows to verify the new column
print(df[['reviewText', 'positivity', 'sentiment_label']].head())

                                          reviewText  positivity  \
0  I'm enjoying these, the fit is about right and...           1
1  these are the coolest little board shorts.  Th...           1
2  beautiful ring for the money, looks very expen...           1
3  I love this dress! Fantastic quality, great st...           1
4  These Ecco golf shoes are differently shaped t...           1

  sentiment_label
0      positivity
1      positivity
2      positivity
3      positivity
4      positivity

C:\Users\HP\AppData\Local\Temp\ipykernel_15356\3905724631.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['sentiment_label'] = np.where(df['positivity'] == 1, 'positivity', 'negative') # jahan pr positivity column mai 1 hai

In [204]:
df.head(10)

,overall,reviewText,summary,positivity,sentiment_label
0,5,"I'm enjoying these, the fit is about right and...",Very comfortable,1,positivity
1,5,these are the coolest little board shorts. Th...,funky board short,1,positivity
2,5,"beautiful ring for the money, looks very expen...",Five Stars,1,positivity
3,5,"I love this dress! Fantastic quality, great st...",I love this dress,1,positivity
4,5,These Ecco golf shoes are differently shaped t...,Still A Great Fit!,1,positivity
5,5,"As a surfer and a city walker, these flip flop...",The best flops I ever bought,1,positivity
6,5,"I bought my shoes from endless.com, with 20%of...",my beautiful yellow wedege,1,positivity
7,5,This is a beautiful scarf and lovely to wear r...,This is a beautiful scarf and lovely to wear r...,1,positivity
8,5,It fits and its warm! Beautiful picture.,Comfy,1,positivity
9,5,Much nicer than the pricepoint would suggest. ...,So convenient!,1,positivity

In [206]:
df.tail()

,overall,reviewText,summary,positivity,sentiment_label
791995,1,Its just like every other shaper uncomfortable...,Just like other shapers,0,negative
791996,1,The fit is fine and they're comfortable. Howev...,Disappointing Quality,0,negative
791997,1,correct size but pops open very easily,not the best,0,negative
791998,1,Only rated this with one star because you didn...,Dont waste your money!,0,negative
791999,1,The product came without the tags on the side!!!,Wrong product,0,negative

In [208]:
y_pred[:11] # ye hmne chek kr lia yahan pr ki kahan kahan pr moel galat predict kr rha hai..

array([1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0])

In [210]:
new_reviews=["Must buy"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [212]:
new_reviews=["did not meet expectations"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [0]

In [214]:
new_reviews=["these are the coolest little board shorts. Th..."]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [216]:
new_reviews = [
    "These are the coolest little board shorts. They have an adjustable waist, which is perfect for my slim little guy. Good quality. Highly recommend."
]


new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [218]:
new_reviews = [
"As a surfer and a city walker, these flip flops are very comfortable and hang on your feet when wet. Yes I would buy another pair but different color. Awesome flops!"
]


new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [1]

In [220]:
new_reviews=["The product came without the tags on the side!!!"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [0]

In [222]:
new_reviews=["The product came without the tags on the side!!!"]

new_review_tfidf = tfidf.transform(new_reviews)
predictions = model.predict(new_review_tfidf)
print("Predictions for new reviews:", predictions)

Predictions for new reviews: [0]

In [224]:
df.head()

,overall,reviewText,summary,positivity,sentiment_label
0,5,"I'm enjoying these, the fit is about right and...",Very comfortable,1,positivity
1,5,these are the coolest little board shorts. Th...,funky board short,1,positivity
2,5,"beautiful ring for the money, looks very expen...",Five Stars,1,positivity
3,5,"I love this dress! Fantastic quality, great st...",I love this dress,1,positivity
4,5,These Ecco golf shoes are differently shaped t...,Still A Great Fit!,1,positivity

In [229]:
# HW
# READ TFIDF
#N MAKE SUMMARY

In [ ]:
# TF-IDF =  TF-IDF (Term Frequency-Inverse Document Frequency)
# FORMULA FOR TF-IDF :  TOTAL  NO.OF FREQUENCY FOR PARTICULAR WORD / TOTAL NO. OF WORDS